<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking Report - MCC IGH</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11px; color: #333; line-height: 1.6; margin: 0; padding: 0; }
        .header { text-align: center; border-bottom: 2px solid {{ $primaryColor }}; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { font-size: 24px; font-weight: 800; color: {{ $primaryColor }}; text-transform: uppercase; margin: 0; }
        .subtitle { font-size: 14px; font-weight: 600; color: #666; margin-top: 5px; }
        .report-info { margin-bottom: 30px; }
        .report-info table { width: 100%; }
        .report-info td { vertical-align: top; }
        .title-box { display: inline-block; padding: 5px 15px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 4px; font-weight: bold; }
        
        table.data-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        table.data-table th { background: #f8fafc; color: #1e293b; font-weight: 700; text-align: left; padding: 10px 8px; border-bottom: 1.5px solid #e2e8f0; }
        table.data-table td { padding: 10px 8px; border-bottom: 1px solid #f1f5f9; vertical-align: top; }
        
        .badge { padding: 2px 6px; border-radius: 3px; font-weight: bold; font-size: 9px; text-transform: uppercase; display: inline-block; white-space: nowrap; }
        .status-paid { background: #dcfce7; color: #166534; }
        .status-pending { background: #fef9c3; color: #854d0e; }
        .status-failed { background: #fee2e2; color: #991b1b; }
        .status-approved { background: #dcfce7; color: #166534; }
        
        .footer { position: fixed; bottom: 0; left: 0; right: 0; text-align: center; font-size: 9px; color: #94a3b8; border-top: 1px solid #f1f5f9; padding-top: 10px; }
        .summary-box { float: right; width: 250px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; margin-top: 20px; }
        .summary-row { display: table; width: 100%; margin-bottom: 5px; }
        .summary-label { display: table-cell; text-align: left; font-weight: bold; }
        .summary-value { display: table-cell; text-align: right; }
        .total-row { border-top: 1.5px solid #e2e8f0; margin-top: 10px; padding-top: 10px; }
        .total-value { font-size: 16px; font-weight: 800; color: {{ $primaryColor }}; }
        
        .clearfix::after { content: ""; clear: both; display: table; }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="logo">MCC International Guest House</h1>
        <p class="subtitle">Official Booking & Revenue Report</p>
    </div>

    <div class="report-info">
        <table>
            <tr>
                <td width="50%">
                    <div class="title-box">REPORT DETAILS</div>
                    <div style="margin-top: 10px;">
                        <strong>Generated On:</strong> {{ now()->format('d M Y, h:i A') }}<br>
                        <strong>Generated By:</strong> Administrator
                    </div>
                </td>
                <td width="50%" align="right">
                    <div class="title-box">FILTERS APPLIED</div>
                    <div style="margin-top: 10px;">
                        <strong>Date Range:</strong> {{ $startDate ?? 'All Time' }} to {{ $endDate ?? 'Present' }}<br>
                        <strong>Total Bookings:</strong> {{ count($bookings) }}
                    </div>
                </td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Guest</th>
                <th>Space / Room</th>
                <th>Stay Schedule</th>
                <th>Payment</th>
                <th align="right">Amount (Rs.)</th>
            </tr>
        </thead>
        <tbody>
            @php $totalPrice = 0; @endphp
            @foreach($bookings as $b)
                @php $totalPrice += $b->total_price; @endphp
                <tr>
                    <td>BK-{{ str_pad($b->id, 5, '0', STR_PAD_LEFT) }}</td>
                    <td>
                        <strong>{{ $b->name }}</strong><br>
                        <span style="color: #64748b; font-size: 9px;">{{ $b->email }}</span>
                    </td>
                    <td>{{ str_replace('-', ' ', ucwords($b->room_name, '- ')) }}</td>
                    <td>
                        {{ \Carbon\Carbon::parse($b->booking_date)->format('d M Y') }}<br>
                        <span style="color: #64748b; font-size: 9px;">{{ \Carbon\Carbon::parse($b->start_time)->format('h:i A') }} - {{ \Carbon\Carbon::parse($b->end_time)->format('h:i A') }}</span>
                    </td>
                    <td>
                        <span class="badge {{ $b->payment_status === 'Paid' ? 'status-paid' : ($b->payment_status === 'Pending' ? 'status-pending' : 'status-failed') }}">
                            {{ strtoupper($b->payment_status) }}
                        </span><br>
                        @if($b->razorpay_payment_id)
                            <span style="color: #94a3b8; font-size: 8px;">{{ $b->razorpay_payment_id }}</span>
                        @endif
                    </td>
                    <td align="right">{{ number_format($b->total_price, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="clearfix">
        <div class="summary-box">
            <div class="summary-row">
                <span class="summary-label">Subtotal Bookings:</span>
                <span class="summary-value">{{ count($bookings) }}</span>
            </div>
            <div class="summary-row total-row">
                <span class="summary-label">TOTAL REVENUE:</span>
                <span class="summary-value total-value">Rs. {{ number_format($totalPrice, 2) }}</span>
            </div>
        </div>
    </div>

    <div class="footer">
        &copy; {{ date('Y') }} MCC International Guest House. All rights reserved. Generated automatically via Admin System.
    </div>
</body>
</html>
